version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12500:12500"   # expose container port 80 to host port 12500
    restart: unless-stopped
