version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:12500"   # expose container port 3000 to host port 12500
    restart: unless-stopped
