version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "12500:12500"
    volumes:
      - jenkins_home:/var/jenkins_home

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      NGROK_AUTHTOKEN: <your-ngrok-token>
      NGROK_PORT: jenkins:12500
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
